[build]
builder = "nixpacks"

[deploy]
startCommand = "sleep 5 && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn myapp.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/users/login/"
healthcheckTimeout = 300
