# Generated by Django 6.0.2 on 2026-02-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MateriaPrima',
            new_name='RawMaterial',
        ),
        migrations.RenameField(
            model_name='movimientoinventario',
            old_name='materia_prima',
            new_name='RawMaterial',
        ),
    ]
