# Generated by Django 6.0.2 on 2026-04-19 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_materiaprima_rawmaterial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='RawMaterial',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='materia_prima',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventory.rawmaterial'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada (Compra)'), ('SALIDA', 'Salida (Merma/Ajuste)'), ('PRODUCCION', 'Salida para Producción')], max_length=15),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unidad_medida',
            field=models.CharField(help_text='Ej: kg, Bulto, Litro', max_length=20),
        ),
    ]
