# Generated by Django 6.0.2 on 2026-02-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoFinal',
            new_name='FinalProduct',
        ),
    ]
