# Generated by Django 6.0.2 on 2026-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_productofinal_finalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
