# Generated by Django 6.0.2 on 2026-03-18 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_venta_direccion_envio_venta_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_entrega_programada',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha_entrega_estimada',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Aceptar'), ('ACEPTADO', 'Aceptado / En Preparación'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
