# Generated by Django 6.0.2 on 2026-03-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_venta_fecha_entrega_programada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproduct',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
