# Generated by Django 6.0.2 on 2026-04-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_materiaprima_rawmaterial_and_more'),
        ('sales', '0006_finalproduct_imagen_alter_finalproduct_codigo_barras'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RegistroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad_insumo_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_paquetes_producidos', models.PositiveIntegerField()),
                ('costo_insumo_momento', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('rendimiento_calculado', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.rawmaterial')),
                ('producto_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.finalproduct')),
            ],
        ),
    ]
