# Generated by Django 6.0.2 on 2026-04-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_venta_estado_alter_venta_usuario_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
