# Generated by Django 6.0.2 on 2026-04-20 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_venta_lat_entrega_venta_lng_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='lat_entrega',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='lng_entrega',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='telefono_contacto',
        ),
        migrations.CreateModel(
            name='MensajePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='sales.venta')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
