# Generated by Django 6.0.2 on 2026-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_remove_venta_lat_entrega_remove_venta_lng_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='lat_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='lng_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
